# Biblioteca numpy

Este tutorial é sobre a utilização da biblioteca numpy, uma biblioteca utilizada para trabalhar com **matrizes**, criada para ser utilizada em computação científica.

O primeiro passo para trabalhar com uma biblioteca no Python é importá-la com a utilização do comando import.

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])   # Cria uma atriz com três elementos
print(type(a))            # Imprime "<class 'numpy.ndarray'>"
print(a.shape)            # Imprime o formato da matriz "(3,)"
print(a[0], a[1], a[2])   # Imprime "1 2 3"
a[0] = 5                  # Altera o valor de um elemento da matriz
print(a)                  # Imprime "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Cria uma matriz bidimensional
print(b.shape)                     # Imprime o formato da matriz "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Imprime "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


## Criação de matrizes
A bilioteca numpy fornece muitas formas diferentes para criar matrizes.

In [9]:
import numpy as np

a = np.zeros((2,2))   # Matriz 2x2 de zeros
print("Matriz a: ")
print(a)
b = np.ones((1,2))    # Matriz 1x2 de uns
print("Matriz b: ")
print(b)              
c = np.full((2,2), 7)  # Cria uma matriz cujos valores são a contante 7
print("Matriz c: ")
print(c)               
d = np.eye(2)         # Cria uma matriz identidade 2x2
print("Matriz d: ")
print(d)              
e = np.random.random((2,2))  # Cria uma matriz 2x2 com valores aleatórios
print("Matriz e: ")
print(e)                     

Matriz a: 
[[0. 0.]
 [0. 0.]]
Matriz b: 
[[1. 1.]]
Matriz c: 
[[7 7]
 [7 7]]
Matriz d: 
[[1. 0.]
 [0. 1.]]
Matriz e: 
[[0.57849269 0.17514776]
 [0.56880274 0.71210545]]


## Slicing de matrizes

Também permite o slicing, visto no tutorial "Introdução ao Python"

In [10]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [13]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

l1_d1 = a[1, :]    # Retira a segunda linha para uma matriz unidimensional
l1_d2 = a[1:2, :]  # Retira a segunda linha para uma matriz bidimensional
print(l1_d1, l1_d1.shape)  # Imprime os valores da segunda linha e respetivo formato
print(l1_d2, l1_d2.shape)  # Imprime os valores da segunda linha e respetivo formato

c1_d1 = a[:, 1]
c1_d2 = a[:, 1:2]
print(c1_d1, c1_d1.shape)
print(c1_d2, c1_d2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


## Indexação de matrizes

A biblioteca numpy permite selecionar elementos de uma matriz tendo por base outras matrizes e expressões booleanas.

In [17]:
#Indexação de matrizes utilizando outras matrizes
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
#Indexação utilizando uma matriz de posições a mostrar
print(a[[0, 1, 2], [0, 1, 0]])
#O exemplo acima pode ser conseguido através de 
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
#Ao utilizar uma matriz de elementos inteiros para indexação podemos reutilizar elementos
print(a[[0, 0], [1, 1]])
#O exemplo acima com outra notação
print(np.array([a[0, 1], a[0, 1]]))


[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [18]:
#Alterar os elementos de posições da matriz
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1])
# Selecionar um elemento de cada linha utilizando os indices em b
print(a[np.arange(4), b])
# Alterar um elemento de cada linha utilizando os indicies em b
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [20]:
#Indexação de matrizes utilizando expressões booleanas
#Utilizado para selecionar os lementos de uma matriz que 
#satisfaçam uma determinada condição
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Tipos de dados

No numpy todos os elementos de uma matriz são de um determinado tipo de dados.

In [22]:
import numpy as np

x = np.array([1, 2])   
print(x.dtype)         
x = np.array([1.0, 2.0])   
print(x.dtype)             
x = np.array([1, 2], dtype=np.int64)   
print(x.dtype)                         

int32
float64
int64


## Aritmétia de matrizes

De seguida aprentam-se algumas operações aritméticas para  a manipulação dos elementos de uma matriz.

In [23]:
#Operacoes ao nível dos elementos das matrizes
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("Soma dos elementos de x com y")
print(x + y)
print(np.add(x, y))

print("Diferenca dos elementos de x com y")
print(x - y)
print(np.subtract(x, y))

print("Multiplicacao dos elementos de x com y")
print(x * y)
print(np.multiply(x, y))

print("Divisao dos elementos de x por y")
print(x / y)
print(np.divide(x, y))

print("Raiz quadrada dos elementos de x")
print(np.sqrt(x))


Soma d
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [24]:
#Operacoes ao nível das matrizes

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print("Produto das matrizes v com w")
print(v.dot(w))
print(np.dot(v, w))

print("Produto das matrizes x com v")
print(x.dot(v))
print(np.dot(x, v))

print("Produto das matrizes x com y")
print(x.dot(y))
print(np.dot(x, y))


Produto das matrizes v com w
219
219
Produto das matrizes x com v
[29 67]
[29 67]
Produto das matrizes x com y
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [25]:
#Operacao soma

import numpy as np

x = np.array([[1,2],[3,4]])

print("Soma todos os elementos de x")
print(np.sum(x))
print("Soma todos os elementos das colunas de x")
print(np.sum(x, axis=0))  
print("Soma todos os elementos das linhas de x")
print(np.sum(x, axis=1))


Soma todos os elementos de x
10
Soma todos os elementos das colunas de x
[4 6]
Soma todos os elementos das linhas de x
[3 7]


## Broadcasting

Mecanismo que permite ao numpy trabalhar com matrizes de diferentes dimensões.

No exemplo seguinte mostra-se como adicionar os valores de uma nova coluna a uma matriz, da forma tradicional e utilizando o mecanismo de broadcasting.

In [26]:
import numpy as np

# Adicionar o vetor v`a cada linha da matriz x guardando na matriz y 
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

print("Metodo 1:")
y = np.empty_like(x)
# Adicionar cada vetor v à matriz y
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

print("Metodo 2:")
y = x + v 
print(y)


Metodo 1:
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Metodo 2:
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Exercícios sobre numpy
1. Crie um vetor com 10 elementos todos a 0
2. Crie uma matriz de zeros com a dimensão de 2X5
3. Crie um vetor de 10 elementos com valores entre 10 e 49
4. Crie uma matriz 2X5 com valores entre 10 e 19
5. Crie uma matriz identidade com a dimensão 5x5
6. Gere uma matriz 5x5 com valores aleatorios
7. Normalize os valores de uma matriz 5x5

In [43]:
import numpy as np
#Solucao 1
print("Solucao 1:")
v = np.zeros(10)
print(v)
#Solucao 2
print("Solucao 2:")
m = np.zeros(shape=(2,5))
print(m)
#Solucao 3
print("Solucao 3:")
v = np.arange(10,50)
print(v)
#Solucao 4
print("Solucao 4:")
m = np.arange(10,20).reshape(2,5)
print(m)
#Solucao 5
print("Solucao 5:")
m = np.eye(5)
print(m)
#Solucao 6
print("Solucao 6:")
m = np.random.random((5,5))
print(m)
#Solucao 7
print("Solucao 7:")
m = np.random.random((5,5))
mmax, mmin = m.max(), m.min()
m = (m - mmin)/(mmax - mmin)
print(m)

Solucao 1:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Solucao 2:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Solucao 3:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Solucao 4:
[[10 11 12 13 14]
 [15 16 17 18 19]]
Solucao 5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Solucao 6:
[[0.76281342 0.74408026 0.1148818  0.24977853 0.71412268]
 [0.60232179 0.37759667 0.71376541 0.37303468 0.81490129]
 [0.43142016 0.04221845 0.89824405 0.28920499 0.3235289 ]
 [0.77774327 0.10184018 0.01459283 0.24731747 0.31458038]
 [0.62006375 0.70798012 0.9686796  0.63054083 0.68064879]]
Solucao 7:
[[0.2682999  0.39677632 0.37944414 0.38243169 0.84963018]
 [0.67628489 0.5124799  0.         0.8910218  0.50559513]
 [0.55275731 0.85354632 0.86499987 0.16524017 0.2618998 ]
 [0.02245695 0.51673857 0.66303025 0.55777495 0.33436236]
 [0.04926232 0.42997615 1.         0.9175554  0.58161408]]


### Exemplo da avaliação da velocidade de execução do numpy

In [ ]:
import numpy as np
from timeit import timeit

